In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder

dataset= pd.read_csv("ExportDemoFile_2022-05-31T13_00_00Z.csv")
dataset.head()
print(dataset)


      x1    x2     y
0    1.0   2.0   5.0
1    2.0   3.0   5.0
2    3.0   5.0   7.0
3    4.0   4.0   9.0
4    5.0   7.0  11.0
5    6.0   6.0  14.0
6    7.0   9.0  15.0
7    8.0  10.0  18.0
8    9.0  11.0  21.0
9   10.0  12.0  20.0
10  11.0  13.0  23.0
11  12.0  13.0  27.0
12  13.0  15.0  27.0
13  14.0  15.0  30.0
14  15.0  16.0  32.0
15  16.0  17.0  33.0
16  17.0  19.0  36.0
17  18.0  19.0  38.0
18  19.0  22.0  40.0
19  20.0  21.0  43.0


In [2]:
X_lin = dataset.drop(['y'],axis=1)
y_lin = dataset[['y']]

X_lin_train, X_lin_test, y_lin_train, y_lin_test = train_test_split(X_lin,y_lin,test_size=0.3,random_state=42)



In [3]:
X_lin_train

x1    x2
11  12.0  13.0
3    4.0   4.0
18  19.0  22.0
16  17.0  19.0
13  14.0  15.0
2    3.0   5.0
9   10.0  12.0
19  20.0  21.0
4    5.0   7.0
12  13.0  15.0
7    8.0  10.0
10  11.0  13.0
14  15.0  16.0
6    7.0   9.0

In [4]:
X_lin_test

x1    x2
0    1.0   2.0
17  18.0  19.0
15  16.0  17.0
1    2.0   3.0
8    9.0  11.0
5    6.0   6.0

In [5]:
y_lin_train

y
11  27.0
3    9.0
18  40.0
16  36.0
13  30.0
2    7.0
9   20.0
19  43.0
4   11.0
12  27.0
7   18.0
10  23.0
14  32.0
6   15.0

In [6]:
y_lin_test

y
0    5.0
17  38.0
15  33.0
1    5.0
8   21.0
5   14.0

In [7]:
Linear_model = LinearRegression()
Linear_model.fit(X_lin_train,y_lin_train)

pred = Linear_model.predict(X_lin_test)

pred


array([[ 2.77287684],
       [38.50475295],
       [34.30100282],
       [ 4.87475191],
       [19.2000679 ],
       [13.67006163]])

In [8]:
Linear_model.score(X_lin_test,pred)


1.0

In [9]:
x_newDataSet = np.array([[21,22],[22,23],[23,24],[24,25]])

# x_newDataSet = {'x1': [1, 2, 3, 4], 'x2': [4, 5, 6, 7]}

x_newDataSet

array([[21, 22],
       [22, 23],
       [23, 24],
       [24, 25]])

In [10]:
NewPred = Linear_model.predict(x_newDataSet)
NewPred

C:\Users\Z004E89B\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[44.81037815],
       [46.91225321],
       [49.01412828],
       [51.11600334]])